version: "3.7"
services:
    # imagem micro 01
    app_sgp:
        build:
            args:
                user: luanramos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis_sgp
        networks:
            - sgp_network

    npm_sgp:
        image: node:20.x
        volumes:
        - .:/var/www
        working_dir: /var/www
        entrypoint: ['npm']
        networks:
            - sgp_network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8020:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - sgp_network

    # mysql micro 01
    db_sgp:
        image: mysql
        platform: linux/arm64/v8
        restart: unless-stopped
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - /var/lib/mysql
        ports:
            - 3308:3306
        networks:
            - sgp_network

    #redis_shorts
    redis_sgp:
        image: redis:latest
        networks:
            - sgp_network

networks:
    sgp_network:
        driver: bridge
